### PR TITLE
Play command

### PR DESCRIPTION
**Pull request by joshuahaddad**

### CODE REVIEW

**Comment by benjamin051000** [comment]
why is this called Play command?

**Review by benjamin051000 — CHANGES_REQUESTED** [review]
Try to use `random.choice` instead of a while loop. I understand this code is pretty minimal, but this is technically not the most efficient implementation. You can get a list of members, just remove Alfred from it and use random.choice. Better complexity

**Comment by joshuahaddad** [comment]
> why is this called Play command?

Whoops

> Try to use `random.choice` instead of a while loop. I understand this code is pretty minimal, but this is technically not the most efficient implementation. You can get a list of members, just remove Alfred from it and use random.choice. Better complexity

I made it so if it chooses any bot it will remove them from the list, pick again, repeat until a normal user is found.  Not sure exactly what random.choice would do

**Comment by joshuahaddad** [comment]
> > why is this called Play command?
> 
> Whoops
> 
> > Try to use `random.choice` instead of a while loop. I understand this code is pretty minimal, but this is technically not the most efficient implementation. You can get a list of members, just remove Alfred from it and use random.choice. Better complexity
> 
> I made it so if it chooses any bot it will remove them from the list, pick again, repeat until a normal user is found. Not sure exactly what random.choice would do

Just added functionality to put a list of people using @ instead of just the people in the room

**Review by benjamin051000 — APPROVED** [review]

**Pull request merged**
